# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ParametersTriangulationWindowTIzNpg.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_parameters_triangulation_mainwindow(object):
    def __init__(self, parameters_triangulation_mainwindow):
        if not parameters_triangulation_mainwindow.objectName():
            parameters_triangulation_mainwindow.setObjectName(u"parameters_triangulation_mainwindow")
        parameters_triangulation_mainwindow.setWindowModality(Qt.WindowModal)
        parameters_triangulation_mainwindow.resize(550, 645)
        icon = QIcon()
        icon.addFile(u"ui/triangle.png", QSize(), QIcon.Normal, QIcon.Off)
        parameters_triangulation_mainwindow.setWindowIcon(icon)
        parameters_triangulation_mainwindow.setAnimated(True)
        self.load_triangulation_action = QAction(parameters_triangulation_mainwindow)
        self.load_triangulation_action.setObjectName(u"load_triangulation_action")
        self.parameters_triangulation_centralwidget = QWidget(parameters_triangulation_mainwindow)
        self.parameters_triangulation_centralwidget.setObjectName(u"parameters_triangulation_centralwidget")
        self.choose_file_button = QPushButton(self.parameters_triangulation_centralwidget)
        self.choose_file_button.setObjectName(u"choose_file_button")
        self.choose_file_button.setGeometry(QRect(350, 10, 181, 41))
        self.height_groupbox = QGroupBox(self.parameters_triangulation_centralwidget)
        self.height_groupbox.setObjectName(u"height_groupbox")
        self.height_groupbox.setGeometry(QRect(20, 400, 331, 71))
        self.min_height_spinbox = QSpinBox(self.height_groupbox)
        self.min_height_spinbox.setObjectName(u"min_height_spinbox")
        self.min_height_spinbox.setGeometry(QRect(40, 30, 111, 31))
        self.min_height_spinbox.setMinimum(-1000000)
        self.min_height_spinbox.setMaximum(1000000)
        self.min_height_label = QLabel(self.height_groupbox)
        self.min_height_label.setObjectName(u"min_height_label")
        self.min_height_label.setGeometry(QRect(10, 30, 31, 31))
        self.max_height_label = QLabel(self.height_groupbox)
        self.max_height_label.setObjectName(u"max_height_label")
        self.max_height_label.setGeometry(QRect(180, 30, 31, 31))
        self.max_height_spinbox = QSpinBox(self.height_groupbox)
        self.max_height_spinbox.setObjectName(u"max_height_spinbox")
        self.max_height_spinbox.setGeometry(QRect(210, 30, 111, 31))
        self.max_height_spinbox.setMinimum(-1000000)
        self.max_height_spinbox.setMaximum(1000000)
        self.start_triangulation_button = QPushButton(self.parameters_triangulation_centralwidget)
        self.start_triangulation_button.setObjectName(u"start_triangulation_button")
        self.start_triangulation_button.setGeometry(QRect(190, 540, 161, 41))
        self.max_discrepancy_label = QLabel(self.parameters_triangulation_centralwidget)
        self.max_discrepancy_label.setObjectName(u"max_discrepancy_label")
        self.max_discrepancy_label.setGeometry(QRect(30, 490, 181, 31))
        self.max_discrepancy_label.setAlignment(Qt.AlignCenter)
        self.max_discrepancy_spinbox = QSpinBox(self.parameters_triangulation_centralwidget)
        self.max_discrepancy_spinbox.setObjectName(u"max_discrepancy_spinbox")
        self.max_discrepancy_spinbox.setGeometry(QRect(220, 490, 111, 31))
        self.max_discrepancy_spinbox.setMinimum(5)
        self.max_discrepancy_spinbox.setMaximum(1000000)
        self.max_discrepancy_spinbox.setValue(5)
        self.step_groupbox = QGroupBox(self.parameters_triangulation_centralwidget)
        self.step_groupbox.setObjectName(u"step_groupbox")
        self.step_groupbox.setGeometry(QRect(360, 400, 161, 131))
        self.step_y_label = QLabel(self.step_groupbox)
        self.step_y_label.setObjectName(u"step_y_label")
        self.step_y_label.setGeometry(QRect(10, 80, 51, 31))
        self.step_y_spinbox = QSpinBox(self.step_groupbox)
        self.step_y_spinbox.setObjectName(u"step_y_spinbox")
        self.step_y_spinbox.setGeometry(QRect(70, 80, 81, 31))
        self.step_y_spinbox.setMinimum(5)
        self.step_y_spinbox.setMaximum(1000000)
        self.step_x_label = QLabel(self.step_groupbox)
        self.step_x_label.setObjectName(u"step_x_label")
        self.step_x_label.setGeometry(QRect(10, 30, 51, 31))
        self.step_x_spinbox = QSpinBox(self.step_groupbox)
        self.step_x_spinbox.setObjectName(u"step_x_spinbox")
        self.step_x_spinbox.setGeometry(QRect(70, 30, 81, 31))
        self.step_x_spinbox.setMinimum(5)
        self.step_x_spinbox.setMaximum(1000000)
        self.step_x_spinbox.setValue(5)
        self.chosen_map_image = QLabel(self.parameters_triangulation_centralwidget)
        self.chosen_map_image.setObjectName(u"chosen_map_image")
        self.chosen_map_image.setGeometry(QRect(10, 60, 521, 321))
        self.chosen_map_image.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.chosen_map_image.setScaledContents(True)
        self.chosen_map_image.setAlignment(Qt.AlignCenter)
        parameters_triangulation_mainwindow.setCentralWidget(self.parameters_triangulation_centralwidget)
        self.height_groupbox.raise_()
        self.start_triangulation_button.raise_()
        self.max_discrepancy_label.raise_()
        self.max_discrepancy_spinbox.raise_()
        self.step_groupbox.raise_()
        self.chosen_map_image.raise_()
        self.choose_file_button.raise_()
        self.parameters_triangulation_menubar = QMenuBar(parameters_triangulation_mainwindow)
        self.parameters_triangulation_menubar.setObjectName(u"parameters_triangulation_menubar")
        self.parameters_triangulation_menubar.setGeometry(QRect(0, 0, 550, 26))
        self.triangulation_menu = QMenu(self.parameters_triangulation_menubar)
        self.triangulation_menu.setObjectName(u"triangulation_menu")
        parameters_triangulation_mainwindow.setMenuBar(self.parameters_triangulation_menubar)
        self.parameters_triangulation_statusbar = QStatusBar(parameters_triangulation_mainwindow)
        self.parameters_triangulation_statusbar.setObjectName(u"parameters_triangulation_statusbar")
        parameters_triangulation_mainwindow.setStatusBar(self.parameters_triangulation_statusbar)

        self.parameters_triangulation_menubar.addAction(self.triangulation_menu.menuAction())
        self.triangulation_menu.addAction(self.load_triangulation_action)
        self.triangulation_menu.addSeparator()

        self.retranslateUi(parameters_triangulation_mainwindow)

        QMetaObject.connectSlotsByName(parameters_triangulation_mainwindow)
    # setupUi

    def retranslateUi(self, parameters_triangulation_mainwindow):
        parameters_triangulation_mainwindow.setWindowTitle(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u041e\u043a\u043d\u043e \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u043e\u0432 \u0442\u0440\u0438\u0430\u043d\u0433\u0443\u043b\u044f\u0446\u0438\u0438", None))
        self.load_triangulation_action.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0438\u0437 \u0444\u0430\u0439\u043b\u0430", None))
#if QT_CONFIG(statustip)
        self.load_triangulation_action.setStatusTip(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0442\u0440\u0438\u0430\u043d\u0433\u0443\u043b\u044f\u0446\u0438\u044e \u0438\u0437 \u0444\u0430\u0439\u043b\u0430", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.choose_file_button.setStatusTip(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0438\u043b\u0438 \u0437\u0430\u043c\u0435\u043d\u0438\u0442\u044c \u043a\u0430\u0440\u0442\u0443 \u0432\u044b\u0441\u043e\u0442", None))
#endif // QT_CONFIG(statustip)
        self.choose_file_button.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u043a\u0430\u0440\u0442\u0443 \u0432\u044b\u0441\u043e\u0442", None))
        self.height_groupbox.setTitle(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0412\u044b\u0441\u043e\u0442\u0430", None))
        self.min_height_spinbox.setSpecialValueText("")
        self.min_height_label.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u041e\u0442", None))
        self.max_height_label.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0414\u043e", None))
        self.max_height_spinbox.setSpecialValueText("")
#if QT_CONFIG(statustip)
        self.start_triangulation_button.setStatusTip(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0417\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u043f\u0440\u043e\u0446\u0435\u0441\u0441 \u0442\u0440\u0438\u0430\u043d\u0433\u0443\u043b\u044f\u0446\u0438\u0438", None))
#endif // QT_CONFIG(statustip)
        self.start_triangulation_button.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0417\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c", None))
        self.max_discrepancy_label.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u043d\u0435\u0432\u044f\u0437\u043a\u0430", None))
        self.max_discrepancy_spinbox.setSpecialValueText("")
        self.step_groupbox.setTitle(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0428\u0430\u0433", None))
        self.step_y_label.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u043f\u043e OY", None))
        self.step_y_spinbox.setSpecialValueText("")
        self.step_x_label.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u043f\u043e OX", None))
        self.step_x_spinbox.setSpecialValueText("")
#if QT_CONFIG(tooltip)
        self.chosen_map_image.setToolTip(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u041a\u0430\u0440\u0442\u0430 \u0432\u044b\u0441\u043e\u0442 \u043d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u0430", None))
#endif // QT_CONFIG(tooltip)
        self.chosen_map_image.setText(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u041a\u0430\u0440\u0442\u0430 \u0432\u044b\u0441\u043e\u0442 \u043d\u0435 \u0432\u044b\u0431\u0440\u0430\u043d\u0430", None))
        self.triangulation_menu.setTitle(QCoreApplication.translate("parameters_triangulation_mainwindow", u"\u0422\u0440\u0438\u0430\u043d\u0433\u0443\u043b\u044f\u0446\u0438\u044f", None))
    # retranslateUi

